# - hosts: kubernetes
#   gather_facts: true
#   remote_user: matheus
#   become: yes
#   become_user: root
#   roles:
#     - { role: commons }
#     - { role: docker }
#     - { role: kubernetes }

- hosts: masters
  gather_facts: true
  remote_user: matheus
  become: yes
  become_user: root
  roles:
#     - { role: masters }
#     - { role: contour }
    - { role: linkerd }

# - hosts: nodes
#   gather_facts: true
#   remote_user: matheus
#   become: yes
#   become_user: root
#   roles:
#     - { role: nodes }